# Generated by Django 4.1.7 on 2023-02-25 11:55

import uuid

import phonenumber_field.modelfields
from django.db import migrations, models

import core_delivery.basemodel


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                ("email", models.CharField(db_index=True, max_length=30, unique=True)),
                ("date_register", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Имя пользователя"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        default="", max_length=50, verbose_name="Отчество пользователя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50, verbose_name="Фамилия пользователя"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(verbose_name="Возраст пользователя"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True, max_length=128, region="RU"
                    ),
                ),
                (
                    "verify",
                    models.BooleanField(
                        default=False, verbose_name="Пользователь верифицирован"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", core_delivery.basemodel.CustomUserManager()),
            ],
        ),
    ]
