# Generated by Django 4.1.7 on 2023-02-25 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_transport_owner"),
        ("users", "0002_deliveryman"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryman",
            name="transport",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveryman",
                to="base.transport",
                verbose_name="Транспортное средство доставщика",
            ),
        ),
        migrations.AlterField(
            model_name="defaultuser",
            name="age",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Возраст пользователя"
            ),
        ),
    ]
