# Generated by Django 4.1.7 on 2023-02-25 14:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_deliveryman_transport_alter_defaultuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryman",
            name="verified",
            field=models.BooleanField(
                default=False, verbose_name="Доставщик верифицирован"
            ),
        ),
        migrations.AlterField(
            model_name="defaultuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True,
                max_length=128,
                region="RU",
                verbose_name="Номер телефона",
            ),
        ),
    ]
