# Generated by Django 4.1.7 on 2023-02-25 12:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PassportData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=50, verbose_name="Отчество"),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "place_of_birth",
                    models.CharField(max_length=200, verbose_name="Место рождения"),
                ),
                ("gender", models.PositiveSmallIntegerField(choices=[])),
                (
                    "series",
                    models.CharField(max_length=4, verbose_name="Серия паспорта"),
                ),
                (
                    "number",
                    models.CharField(max_length=6, verbose_name="Номер паспорта"),
                ),
                (
                    "expired_date",
                    models.DateField(verbose_name="Дата истечения паспорта"),
                ),
                (
                    "verify",
                    models.BooleanField(
                        default=False, verbose_name="Паспорт верифицирован"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
