# Generated by Django 4.1.7 on 2023-02-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_deliveryman"),
        ("base", "0002_transport"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.deliveryman"
            ),
        ),
    ]
