# Generated by Django 4.1.7 on 2023-02-25 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_transport_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transport",
            name="owner",
        ),
    ]
