# Generated by Django 4.1.7 on 2023-02-25 17:25

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_alter_deliveryman_passport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=30, verbose_name="Что находится в этой точке"
                    ),
                ),
                ("how_to_find", models.TextField(verbose_name="Как найти")),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Географическая точка"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "content",
                    models.CharField(max_length=30, verbose_name="Содержание заказа"),
                ),
                ("description", models.TextField(verbose_name="Доп. информация")),
                ("fragile", models.BooleanField(verbose_name="Хрупкий")),
                (
                    "distance",
                    models.FloatField(verbose_name="Расстояние между точками"),
                ),
                (
                    "delivered",
                    models.BooleanField(default=False, verbose_name="Доставлено"),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Оплачено")),
                (
                    "delivery_price",
                    models.FloatField(
                        default=0, verbose_name="Полная цена за доставку"
                    ),
                ),
                (
                    "payment",
                    models.FloatField(default=0, verbose_name="Оплата доставщику"),
                ),
                ("weight", models.FloatField(verbose_name="Вес отправления")),
                ("dimension", models.JSONField(verbose_name="Габариты отправления")),
                (
                    "delivery_man",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="del_orders",
                        to="users.deliveryman",
                        verbose_name="Доставщик",
                    ),
                ),
                (
                    "delivery_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="del_ord",
                        to="orders.location",
                        verbose_name="Точка доставки",
                    ),
                ),
                (
                    "dispatch_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dis_ord",
                        to="orders.location",
                        verbose_name="Точка отправки",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rec_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReceiverReview",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "text",
                    models.TextField(default="", verbose_name="Комментарий доставщика"),
                ),
                ("evaluation", models.PositiveSmallIntegerField(verbose_name="Оценка")),
                (
                    "deliveryman",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.deliveryman",
                        verbose_name="Доставщик",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                ("description", models.TextField(verbose_name="Описание инцидента")),
                (
                    "files",
                    models.FileField(
                        upload_to="", verbose_name="Прикрепленные файлы/фото/видео"
                    ),
                ),
                (
                    "employee_answer",
                    models.TextField(
                        verbose_name="Ответ работника принявшего инцидент"
                    ),
                ),
                (
                    "incident_handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто обработал инцидент",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                        verbose_name="Заказ с которым произошел инцидент",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalOrderRecord",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                ("start_time", models.TimeField(verbose_name="Старт доставки")),
                ("end_time", models.TimeField(verbose_name="Конец доставки")),
                (
                    "receiving_time",
                    models.TimeField(verbose_name="Время получения заказа доставщиком"),
                ),
                (
                    "log_id",
                    models.UUIDField(verbose_name="UUID лога перемещения доставщика"),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.incident",
                        verbose_name="Инцидент",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryManReview",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date_modified", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "text",
                    models.TextField(default="", verbose_name="Комментарий получателя"),
                ),
                ("evaluation", models.PositiveSmallIntegerField(verbose_name="Оценка")),
                (
                    "deliveryman",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.deliveryman",
                        verbose_name="Доставщик",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
