# Generated by Django 4.1.7 on 2023-02-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="published",
            field=models.BooleanField(
                default=False, verbose_name="Опубликовано в очередь"
            ),
        ),
    ]
